// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_HEADERS_H_
#define _BEHAVIAC_HEADERS_H_

#include "behaviac/behaviac.h"

// YOU SHOULD SET THE HEADER FILES OF YOUR GAME WHEN EXPORTING CPP FILES ON THE BEHAVIAC EDITOR:
#include "../../../Agent/AgentArrayAccessTest.h"
#include "../../../Agent/AgentNodeTest.h"
#include "../../../Agent/CustomPropertyAgent.h"
#include "../../../Agent/EmployeeParTestAgent.h"
#include "../../../Agent/FSMAgentTest.h"
#include "../../../Agent/HTNAgentHouse.h"
#include "../../../Agent/HTNAgentHouseBase.h"
#include "../../../Agent/HTNAgentTravel.h"
#include "../../../Agent/ParTestAgent.h"
#include "../../../Agent/ParTestAgentBase.h"
#include "../../../Agent/ParTestRegNameAgent.h"
#include "../../../Agent/PreconEffectorAgent.h"
#include "../../../Agent/PropertyReadonlyAgent.h"
#include "../../../Agent/UnitTestTypes.h"

#include "behaviac_customized_types.h"

#endif // _BEHAVIAC_HEADERS_H_
