// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_behaviac_EBTStatus : ICompareValue<behaviac.EBTStatus>
	{
		public override bool Equal(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(behaviac.EBTStatus lhs, behaviac.EBTStatus rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_IList : ICompareValue<IList>
	{
		public override bool Equal(IList lhs, IList rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(IList lhs, IList rhs)
		{
			return !Equal(lhs, rhs);
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 2970163408;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// CBTPlayer
			meta = new AgentMeta(2259110346);
			AgentMeta._AgentMetas_[2361377009] = meta;
			meta.RegisterMemberProperty(1881561774, new CMemberProperty<int>("m_Frames", delegate(Agent self, int value) { ((CBTPlayer)self).m_Frames = value; }, delegate(Agent self) { return ((CBTPlayer)self).m_Frames; }));
			meta.RegisterMemberProperty(3476008754, new CMemberProperty<uint>("m_iBaseSpeed", delegate(Agent self, uint value) { ((CBTPlayer)self).m_iBaseSpeed = value; }, delegate(Agent self) { return ((CBTPlayer)self).m_iBaseSpeed; }));
			meta.RegisterMethod(3088088344, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((CBTPlayer)self).Action1(); }));
			meta.RegisterMethod(2317754266, new CAgentMethod<behaviac.EBTStatus>(delegate(Agent self) { return ((CBTPlayer)self).Action3(); }));
			meta.RegisterMethod(4094979492, new CAgentMethod<bool>(delegate(Agent self) { return ((CBTPlayer)self).Condition(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { CBTPlayer.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<CBTPlayer>("CBTPlayer");
			AgentMeta.Register<behaviac.EBTStatus>("behaviac.EBTStatus");
			ComparerRegister.RegisterType<behaviac.EBTStatus, CompareValue_behaviac_EBTStatus>();
			AgentMeta.Register<IList>("IList");
			ComparerRegister.RegisterType<IList, CompareValue_IList>();

			Agent.RegisterInstanceName<CBTPlayer>("CBTPlayer");
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<CBTPlayer>("CBTPlayer");
			AgentMeta.UnRegister<behaviac.EBTStatus>("behaviac.EBTStatus");
			AgentMeta.UnRegister<IList>("IList");

			Agent.UnRegisterInstanceName<CBTPlayer>("CBTPlayer");
			return true;
		}
	}
}
