// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct PROPERTY_TYPE_CBTPlayer_m_iBaseSpeed { };
template<> inline unsigned int& CBTPlayer::_Get_Property_<PROPERTY_TYPE_CBTPlayer_m_iBaseSpeed>()
{
	return this->m_iBaseSpeed;
}

struct METHOD_TYPE_CBTPlayer_Action1 { };
template<> inline behaviac::EBTStatus CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Action1>()
{
	return this->CBTPlayer::Action1();
}

struct METHOD_TYPE_CBTPlayer_Action3 { };
template<> inline behaviac::EBTStatus CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Action3>()
{
	return this->CBTPlayer::Action3();
}

struct METHOD_TYPE_CBTPlayer_Condition { };
template<> inline bool CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_Condition>()
{
	return this->CBTPlayer::Condition();
}

struct METHOD_TYPE_CBTPlayer_MoveAhead { };
template<> inline void CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_MoveAhead>(int p0)
{
	this->CBTPlayer::MoveAhead(p0);
}

struct METHOD_TYPE_CBTPlayer_MoveBack { };
template<> inline void CBTPlayer::_Execute_Method_<METHOD_TYPE_CBTPlayer_MoveBack>(int p0)
{
	this->CBTPlayer::MoveBack(p0);
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
