// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../types/behaviac_types.h"

namespace behaviac
{
	class bt_node_test_selector_stochastic_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_4
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_selector_ut_5
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_stochastic_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_stochastic_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_stochastic_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_stochastic_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_sequence_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

}
