// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../types/behaviac_types.h"

namespace behaviac
{
	class bt_node_test_PreconditionEffectorTest_PreconditionEffectorTest_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_repeat_repeat_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_repeat_repeat_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_child_agent_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_noop_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_3
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_waitforsignal_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_waitforsignal_1
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_ut_waitforsignal_2
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_action_waitframes_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_circular_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

	class bt_node_test_condition_ut_0
	{
	public:
		static bool Create(BehaviorTree* pBT);
	};

}
