// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_CUSTOMIZED_TYPES_H_
#define _BEHAVIAC_CUSTOMIZED_TYPES_H_

#include "behaviac/agent/agent.h"

// -------------------
// Customized enums
// -------------------

// -------------------
// Customized structs
// -------------------

BEHAVIAC_EXTEND_EXISTING_TYPE_EX(IList, false);
BEHAVIAC_DECLARE_TYPE_VECTOR_HANDLER(IList);

template< typename SWAPPER >
inline void SwapByteImplement(IList& v)
{
}

namespace behaviac
{
	namespace PrivateDetails
	{
		template<>
		inline bool Equal(const IList& lhs, const IList& rhs)
		{
			return &lhs == &rhs;
		}
	}
}

BEHAVIAC_EXTEND_EXISTING_TYPE_EX(System::Object, false);
BEHAVIAC_DECLARE_TYPE_VECTOR_HANDLER(System::Object);

template< typename SWAPPER >
inline void SwapByteImplement(System::Object& v)
{
}

namespace behaviac
{
	namespace PrivateDetails
	{
		template<>
		inline bool Equal(const System::Object& lhs, const System::Object& rhs)
		{
			return &lhs == &rhs;
		}
	}
}

#endif // _BEHAVIAC_CUSTOMIZED_TYPES_H_
