// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../cs/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: LoopBT

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoop_bt_LoopBT_node1 : behaviac.DecoratorLoop
	{
		public DecoratorLoop_bt_LoopBT_node1()
		{
			m_bDecorateWhenChildEnds = true;
			m_bDoneWithinFrame = false;
		}
		protected override int GetCount(Agent pAgent)
		{
			return 3;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_LoopBT_node0 : behaviac.Action
	{
		public Action_bt_LoopBT_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_LoopBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("LoopBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				DecoratorLoop_bt_LoopBT_node1 node1 = new DecoratorLoop_bt_LoopBT_node1();
				node1.SetClassNameString("DecoratorLoop");
				node1.SetId(1);
#if !BEHAVIAC_RELEASE
				node1.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node1);
				{
					Action_bt_LoopBT_node0 node0 = new Action_bt_LoopBT_node0();
					node0.SetClassNameString("Action");
					node0.SetId(0);
#if !BEHAVIAC_RELEASE
					node0.SetAgentType("FirstAgent");
#endif
					node1.AddChild(node0);
					node1.SetHasEvents(node1.HasEvents() | node0.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node1.HasEvents());
			}
			return true;
		}
	}

	// Source file: SelectBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_SelectBT_node4 : behaviac.Assignment
	{
		public Assignment_bt_SelectBT_node4()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 6;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SelectBT_node2 : behaviac.Condition
	{
		public Condition_bt_SelectBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 8;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SelectBT_node0 : behaviac.Action
	{
		public Action_bt_SelectBT_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_SelectBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SelectBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node3 = new Sequence();
				node3.SetClassNameString("Sequence");
				node3.SetId(3);
#if !BEHAVIAC_RELEASE
				node3.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node3);
				{
					Assignment_bt_SelectBT_node4 node4 = new Assignment_bt_SelectBT_node4();
					node4.SetClassNameString("Assignment");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("FirstAgent");
#endif
					node3.AddChild(node4);
					node3.SetHasEvents(node3.HasEvents() | node4.HasEvents());
				}
				{
					Selector node1 = new Selector();
					node1.SetClassNameString("Selector");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node3.AddChild(node1);
					{
						Condition_bt_SelectBT_node2 node2 = new Condition_bt_SelectBT_node2();
						node2.SetClassNameString("Condition");
						node2.SetId(2);
#if !BEHAVIAC_RELEASE
						node2.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node2);
						node1.SetHasEvents(node1.HasEvents() | node2.HasEvents());
					}
					{
						Action_bt_SelectBT_node0 node0 = new Action_bt_SelectBT_node0();
						node0.SetClassNameString("Action");
						node0.SetId(0);
#if !BEHAVIAC_RELEASE
						node0.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node0);
						node1.SetHasEvents(node1.HasEvents() | node0.HasEvents());
					}
					node3.SetHasEvents(node3.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node3.HasEvents());
			}
			return true;
		}
	}

	// Source file: SequenceBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_SequenceBT_node3 : behaviac.Assignment
	{
		public Assignment_bt_SequenceBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 6;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SequenceBT_node2 : behaviac.Condition
	{
		public Condition_bt_SequenceBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 8;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SequenceBT_node0 : behaviac.Action
	{
		public Action_bt_SequenceBT_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_SequenceBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SequenceBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node1 = new Sequence();
				node1.SetClassNameString("Sequence");
				node1.SetId(1);
#if !BEHAVIAC_RELEASE
				node1.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node1);
				{
					Assignment_bt_SequenceBT_node3 node3 = new Assignment_bt_SequenceBT_node3();
					node3.SetClassNameString("Assignment");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node1.AddChild(node3);
					node1.SetHasEvents(node1.HasEvents() | node3.HasEvents());
				}
				{
					Condition_bt_SequenceBT_node2 node2 = new Condition_bt_SequenceBT_node2();
					node2.SetClassNameString("Condition");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node1.AddChild(node2);
					node1.SetHasEvents(node1.HasEvents() | node2.HasEvents());
				}
				{
					Action_bt_SequenceBT_node0 node0 = new Action_bt_SequenceBT_node0();
					node0.SetClassNameString("Action");
					node0.SetId(0);
#if !BEHAVIAC_RELEASE
					node0.SetAgentType("FirstAgent");
#endif
					node1.AddChild(node0);
					node1.SetHasEvents(node1.HasEvents() | node0.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node1.HasEvents());
			}
			return true;
		}
	}

}
