// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers

namespace behaviac
{
}


struct PROPERTY_TYPE_SecondAgent_p1 { };
template<> inline int& SecondAgent::_Get_Property_<PROPERTY_TYPE_SecondAgent_p1>()
{
	unsigned char* pc = (unsigned char*)this;
	pc += (int)BEHAVIAC_OFFSETOF(SecondAgent, SecondAgent::p1);
	return *(reinterpret_cast<int*>(pc));
}

struct METHOD_TYPE_SecondAgent_m1 { };
template<> inline void SecondAgent::_Execute_Method_<METHOD_TYPE_SecondAgent_m1>(behaviac::string& p0)
{
	this->SecondAgent::m1(p0);
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
