// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "FirstAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

FirstAgent::FirstAgent()
{
	p1 = 0;
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR
	count = 0;
///<<< END WRITING YOUR CODE
}

FirstAgent::~FirstAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

void FirstAgent::Start()
{
///<<< BEGIN WRITING YOUR CODE Start
	count = 0;
///<<< END WRITING YOUR CODE
}

behaviac::EBTStatus FirstAgent::Wait()
{
///<<< BEGIN WRITING YOUR CODE Wait
	count++;

	printf("p1 = %i\n", p1);

	if (count == 10000)
	{
		return behaviac::BT_SUCCESS;
	}

	return behaviac::BT_RUNNING;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
